// source: tutorial.hierarchy.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.ClientToLogin');
goog.provide('proto.ClientToLogin.MsgCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ClientToLoginMessage');
goog.require('proto.ClientToLoginReq');
goog.require('proto.ClientToLoginRes');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ClientToLogin = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ClientToLogin.oneofGroups_);
};
goog.inherits(proto.ClientToLogin, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ClientToLogin.displayName = 'proto.ClientToLogin';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ClientToLogin.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.ClientToLogin.MsgCase = {
  MSG_NOT_SET: 0,
  REQUEST: 1,
  RESPONSE: 2,
  MESSAGE: 3
};

/**
 * @return {proto.ClientToLogin.MsgCase}
 */
proto.ClientToLogin.prototype.getMsgCase = function() {
  return /** @type {proto.ClientToLogin.MsgCase} */(jspb.Message.computeOneofCase(this, proto.ClientToLogin.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ClientToLogin.prototype.toObject = function(opt_includeInstance) {
  return proto.ClientToLogin.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ClientToLogin} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ClientToLogin.toObject = function(includeInstance, msg) {
  var f, obj = {
    request: (f = msg.getRequest()) && proto.ClientToLoginReq.toObject(includeInstance, f),
    response: (f = msg.getResponse()) && proto.ClientToLoginRes.toObject(includeInstance, f),
    message: (f = msg.getMessage()) && proto.ClientToLoginMessage.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ClientToLogin}
 */
proto.ClientToLogin.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ClientToLogin;
  return proto.ClientToLogin.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ClientToLogin} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ClientToLogin}
 */
proto.ClientToLogin.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ClientToLoginReq;
      reader.readMessage(value,proto.ClientToLoginReq.deserializeBinaryFromReader);
      msg.setRequest(value);
      break;
    case 2:
      var value = new proto.ClientToLoginRes;
      reader.readMessage(value,proto.ClientToLoginRes.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 3:
      var value = new proto.ClientToLoginMessage;
      reader.readMessage(value,proto.ClientToLoginMessage.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ClientToLogin.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ClientToLogin.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ClientToLogin} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ClientToLogin.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRequest();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ClientToLoginReq.serializeBinaryToWriter
    );
  }
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ClientToLoginRes.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ClientToLoginMessage.serializeBinaryToWriter
    );
  }
};


/**
 * optional ClientToLoginReq request = 1;
 * @return {?proto.ClientToLoginReq}
 */
proto.ClientToLogin.prototype.getRequest = function() {
  return /** @type{?proto.ClientToLoginReq} */ (
    jspb.Message.getWrapperField(this, proto.ClientToLoginReq, 1));
};


/**
 * @param {?proto.ClientToLoginReq|undefined} value
 * @return {!proto.ClientToLogin} returns this
*/
proto.ClientToLogin.prototype.setRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.ClientToLogin.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ClientToLogin} returns this
 */
proto.ClientToLogin.prototype.clearRequest = function() {
  return this.setRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ClientToLogin.prototype.hasRequest = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ClientToLoginRes response = 2;
 * @return {?proto.ClientToLoginRes}
 */
proto.ClientToLogin.prototype.getResponse = function() {
  return /** @type{?proto.ClientToLoginRes} */ (
    jspb.Message.getWrapperField(this, proto.ClientToLoginRes, 2));
};


/**
 * @param {?proto.ClientToLoginRes|undefined} value
 * @return {!proto.ClientToLogin} returns this
*/
proto.ClientToLogin.prototype.setResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.ClientToLogin.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ClientToLogin} returns this
 */
proto.ClientToLogin.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ClientToLogin.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ClientToLoginMessage message = 3;
 * @return {?proto.ClientToLoginMessage}
 */
proto.ClientToLogin.prototype.getMessage = function() {
  return /** @type{?proto.ClientToLoginMessage} */ (
    jspb.Message.getWrapperField(this, proto.ClientToLoginMessage, 3));
};


/**
 * @param {?proto.ClientToLoginMessage|undefined} value
 * @return {!proto.ClientToLogin} returns this
*/
proto.ClientToLogin.prototype.setMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.ClientToLogin.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ClientToLogin} returns this
 */
proto.ClientToLogin.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ClientToLogin.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


