<?php

///////////////////////////////////////////////////////////////////////////////
/// @file Reflection.inc
/// @title 
/// @brief 
///
/// @author
/// @date 2014. 8. 24. 오전 11:35:46
///////////////////////////////////////////////////////////////////////////////


namespace ObjectGroup 
{
	/**
	 * Constant :
	 * Max object count !!!
	 */
	const MAX_OBJECT_COUNT = 10;
	
	
	/**
	 * 
	 * Class :
	 * BaseObject
	 *
	 */
	class BaseObject 
	{
		/**
		 * This is an member constant
		 */		
		const NAME = 'boss';
		
		/**
		 * This is an member function
		 */		
		public function fn() { }
	}
}


?>