// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: protocol.Packet.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Item
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"UUID")]
        public ulong Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"TID")]
        public uint Tid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Character
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"UUID")]
        public ulong Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"TID")]
        public uint Tid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"item")]
        public global::System.Collections.Generic.List<Item> Items { get; } = new global::System.Collections.Generic.List<Item>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Player
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"UUID")]
        public ulong Uuid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"nickname")]
        public byte[] Nickname { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"character")]
        public global::System.Collections.Generic.List<Character> Characters { get; } = new global::System.Collections.Generic.List<Character>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
