// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: tutorial.hierarchy.proto

#pragma warning disable CS1591, CS0612, CS3021

[global::ProtoBuf.ProtoContract()]
public partial class MyHomeObjectSlotInfo
{
    [global::ProtoBuf.ProtoMember(1)]
    public int slotNum { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public int objectId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClientToLoginReq
{
    [global::ProtoBuf.ProtoMember(1)]
    public LoginReq loginReq
    {
        get { return __pbn__msg.Is(1) ? ((LoginReq)__pbn__msg.Object) : default(LoginReq); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
    }
    public bool ShouldSerializeloginReq() => __pbn__msg.Is(1);
    public void ResetloginReq() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__msg;

    [global::ProtoBuf.ProtoMember(2)]
    public LogoutReq logoutReq
    {
        get { return __pbn__msg.Is(2) ? ((LogoutReq)__pbn__msg.Object) : default(LogoutReq); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
    }
    public bool ShouldSerializelogoutReq() => __pbn__msg.Is(2);
    public void ResetlogoutReq() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 2);

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string securtyToken { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogoutReq
    {
    }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClientToLoginRes
{
    [global::ProtoBuf.ProtoMember(1)]
    public LoginServerErrorCode errorCode { get; set; }

    [global::ProtoBuf.ProtoMember(2)]
    public LoginRes loginRes
    {
        get { return __pbn__msg.Is(2) ? ((LoginRes)__pbn__msg.Object) : default(LoginRes); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
    }
    public bool ShouldSerializeloginRes() => __pbn__msg.Is(2);
    public void ResetloginRes() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 2);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__msg;

    [global::ProtoBuf.ProtoMember(3)]
    public LogoutRes logoutRes
    {
        get { return __pbn__msg.Is(3) ? ((LogoutRes)__pbn__msg.Object) : default(LogoutRes); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
    }
    public bool ShouldSerializelogoutRes() => __pbn__msg.Is(3);
    public void ResetlogoutRes() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 3);

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRes
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string gameServerAddr { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int gameServerPort { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"otp")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Otp { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LogoutRes
    {
    }

    [global::ProtoBuf.ProtoContract()]
    public enum LoginServerErrorCode
    {
        Success = 0,
        DupLogin = 1,
        Moving = 2,
        DbError = 3,
        KickFail = 4,
        NotCorrectPassword = 5,
        NotFoundUser = 6,
        NoGameServer = 7,
        LoginPending = 8,
    }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClientToLoginMessage
{
    [global::ProtoBuf.ProtoMember(1)]
    public MyHome myHome { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class MyHome
    {
        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"slotInfo")]
        public global::System.Collections.Generic.List<MyHomeObjectSlotInfo> slotInfoes { get; } = new global::System.Collections.Generic.List<MyHomeObjectSlotInfo>();

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class ClientToLogin
{
    [global::ProtoBuf.ProtoMember(1, Name = @"request")]
    public ClientToLoginReq Request
    {
        get { return __pbn__msg.Is(1) ? ((ClientToLoginReq)__pbn__msg.Object) : default(ClientToLoginReq); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
    }
    public bool ShouldSerializeRequest() => __pbn__msg.Is(1);
    public void ResetRequest() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__msg;

    [global::ProtoBuf.ProtoMember(2, Name = @"response")]
    public ClientToLoginRes Response
    {
        get { return __pbn__msg.Is(2) ? ((ClientToLoginRes)__pbn__msg.Object) : default(ClientToLoginRes); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
    }
    public bool ShouldSerializeResponse() => __pbn__msg.Is(2);
    public void ResetResponse() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 2);

    [global::ProtoBuf.ProtoMember(3, Name = @"message")]
    public ClientToLoginMessage Message
    {
        get { return __pbn__msg.Is(3) ? ((ClientToLoginMessage)__pbn__msg.Object) : default(ClientToLoginMessage); }
        set { __pbn__msg = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
    }
    public bool ShouldSerializeMessage() => __pbn__msg.Is(3);
    public void ResetMessage() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__msg, 3);

}

#pragma warning restore CS1591, CS0612, CS3021
