// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: protocol.CommandType.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public enum CommandType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAYER_INFO_UPDATE")]
        PlayerInfoUpdate = 3001,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
